### ISSUE TITLE
Exception: Server does not support security type "vncAuthentication"

### ISSUE THREAD

**Issue by PoojaSachanTechglock** [Goddchen/dart-rfb#19]
Hi its giving error
Exception: Server does not support security type "vncAuthentication"

I am using RealVNC server and Auth Scheme is set to VNC password.

**Comment by Goddchen** [comment]
Hey! That sounds strange. Are you sure you are using the latest version? I mean, the one where `vncAuthentication` was added, and not a version before that? If you are on the latest version, could you maybe please debug and see that kind of security type is negotiated during the handshake?
