### ISSUE TITLE
Client listening mode support

### ISSUE THREAD

**Issue by jaychouwii** [Goddchen/dart-rfb#23]
Hey, thanks for the useful library so far!
Are there any plans for supporting listening mode（reverse）？
like this

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/installation_guide/sn-remoteaccess-installation-vnclistener

28.2.2. Connecting the Installation System to a VNC Listener
To have the installation system automatically connect to a VNC client, first start the client in listening mode. On Red Hat Enterprise Linux systems, use the option to run vncviewer as a listener. In a terminal window, enter the command: -listen
  
 vncviewer -listen

Note
By default, vncviewer uses TCP port 5500 when in listening mode. The firewall must be configured to permit connections to this port from other systems. Choose System → Administration → Firewall. Select Other ports, and Add. Enter 5500 in the Port(s) field, and specify tcp as the Protocol.

Once the listening client is active, start the installation system and set the VNC options at the prompt. In addition to and options, use the option to specify the name or IP address of the system that has the listening client. To specify the TCP port for the listener, add a colon and the port number to the name of the system. boot:vncvncpasswordvncconnect
For example, to connect to a VNC client on the system on the port 5500, enter the following at the prompt: desktop.mydomain.comboot:

linux vnc vncpassword=qwerty vncconnect=desktop.mydomain.com:5500

**Comment by Goddchen** [comment]
Haven't checked it out yet (didn't even know this existed 😉 ). Currently there is not plan to implement it. I'm not even sure if this is the correct package to implement it or `flutter_rfb` would be better. Or the part of the protocol here and the client/listen logic part in `flutter_rfb`. I'd have to dive deeper into the reference docs to first understand how this whole thing works.

But if you really need it, feel free to invest the time and create a PR. I'll happily review it.
